name: Commit Build module

on:
  push:
    branches: [ main ] # 根据实际情况替换分支名

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 设置为 0 以获取所有标签历史

      - name: Create empty folders
        run: |
           mkdir -p files/modules/
           mkdir -p files/patches/
           mkdir -p files/patches/apks
           mkdir -p files/patches/modules
           mkdir -p files/patches/sdcard
           mkdir -p files/patches/data
           mkdir -p settings/

      - name: Get current time
        run: |
          random_number=$((RANDOM % 100))
          timestamp_with_random="$(date +'%Y%m%d')${random_number}"
          echo "$timestamp_with_random" > current_time.txt
          
      - name: Get latest tag
        id: latest-tag
        run: |
              LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
              echo "$LATEST_TAG" > latest_tag.txt

      - name: Make module.prop
        run: |
            LATEST_TAG=$(cat latest_tag.txt)
            CURRENT_TIME=$(cat current_time.txt)
            . ./settings/settings.sh
            echo "id=${MODULE_ID}" > module.prop
            echo "name=${MODULE_NAME}" >> module.prop
            echo "version=${LATEST_TAG}" >> module.prop
            echo "versionCode=${CURRENT_TIME}" >> module.prop
            echo "author=AuroraNasa" >> module.prop
            echo "description=${MODULE_DES}" >> module.prop
            cat module.prop
            rm latest_tag.txt
            rm current_time.txt

      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
          
      - name: Upload zip files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}_${{ env.SHORT_SHA }}
          path: |
            *