name: Build module release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 设置为 0 以获取所有标签历史

      - name: Create necessary directories
        run: |
          mkdir -p files/modules
          mkdir -p files/patches/{apks,modules,sdcard,data}
          mkdir -p settings

      - name: Install 7z
        uses: edgarrc/action-7z@v1.0.5

      - name: Get current time
        run: |
          random_number=$((RANDOM % 100))
          timestamp_with_random="$(date +'%Y%m%d')${random_number}"
          echo "$timestamp_with_random" > current_time.txt

      - name: Get latest tag
        id: latest-tag
        run: |
            LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
            echo "$LATEST_TAG" > latest_tag.txt

      - name: Compress repository for each language version
        run: |
            LATEST_TAG=$(cat latest_tag.txt)
            CURRENT_TIME=$(cat current_time.txt)
            . ./settings/settings.sh
            echo "id=${MODULE_ID}" > module.prop
            echo "name=${MODULE_NAME}" >> module.prop
            echo "version=${LATEST_TAG}" >> module.prop
            echo "versionCode=${CURRENT_TIME}" >> module.prop
            echo "author=AuroraNasa" >> module.prop
            echo "description=${MODULE_DES}" >> module.prop
            cat module.prop
            7z a -r -mx9 "${MODULE_NAME}_${LATEST_TAG}.zip" * -x!*.git* -x!*.zip -x!latest_tag.txt -x!current_time.txt

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.zip
